name: Run MLB DFS R Script

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI
  schedule:
    # Mon–Fri: 10:30 a.m. – 4:00 p.m. ET (14:30–20:00 UTC) every 30 minutes
    - cron: '30 14-19 * * 1-5'  # :30 of each hour
    - cron: '0 15-19 * * 1-5'   # :00 of each hour
    - cron: '0 20 * * 1-5'      # final run at 4:00 p.m. ET

    # Mon–Fri: 4:00 p.m. – 7:30 p.m. ET (20:00–23:30 UTC) every 15 minutes
    - cron: '*/15 20-23 * * 1-5'

    # Mon–Fri: 7:30 p.m. – 10:00 p.m. ET (23:30–02:00 UTC next day)
    - cron: '30 23 * * 1-5'     # 7:30 p.m. ET
    - cron: '0,30 0-1 * * 2-6'  # 8:00, 8:30, 9:00, 9:30 p.m. ET (next day UTC)

    # Sat–Sun: 10:30 a.m. to 7:00 p.m. ET (14:30–23:00 UTC) every 30 minutes
    - cron: '30 14-22 * * 6,0'  # :30 from 10:30 a.m. to 6:30 p.m. ET
    - cron: '0 15-23 * * 6,0'   # :00 from 11:00 a.m. to 7:00 p.m. ET

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('googlesheets4', 'googledrive', 'dplyr', 'lubridate', 'stringr', 'rjson', 'httr', 'base64enc', 'magrittr', 'plyr', 'RCurl', 'XML'), repos = 'https://cloud.r-project.org')"

    - name: Check installed R packages
      run: |
        Rscript -e 'cat("Loaded packages:\n"); print(.packages())'
    
    - name: Run R script
      env:
        GCP_SHEETS_KEY_B64: ${{ secrets.GCP_SHEETS_KEY_B64 }}
      run: |
        Rscript "MLB DFS.R"

