name: Run MLB DFS R Script

on:
  schedule:
    # Runs every 15 minutes between 10:00 AM ET and 9:30 PM ET (2:00 PM to 1:30 AM UTC)
    - cron: '0,15,30,45 14-20 * * *'
  workflow_dispatch:  # Allow manual trigger from GitHub Actions UI

jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: ~/.R/library

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        install.packages(c(
          "googlesheets4", "googledrive", "dplyr", "lubridate",
          "stringr", "rjson", "httr", "base64enc", "magrittr",
          "plyr", "RCurl", "XML", "jsonlite"
        ))

    - name: Run R script
      run: |
        Rscript -e 'cat("Loaded packages:\n"); print(.packages())'
        Rscript "MLB Hitting Data w-API.R"
