name: Run MLB DFS R Script

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI
  schedule:
    # Every day: 11:00 AM – 1:30 PM ET (every 15 minutes)
    - cron: '0,15,30,45 16-18 * * *'  # Every 15 minutes from 11:00 AM – 1:30 PM ET (16:00–18:30 UTC)

    # Every day: 1:30 PM – 5:30 PM ET (every 30 minutes)
    - cron: '0,30 19-22 * * *'        # Every 30 minutes from 1:30 PM – 5:30 PM ET (19:00–22:30 UTC)

    # Every day: 5:30 PM – 10:00 PM ET (every 15 minutes)
    - cron: '0,15,30,45 22-30 * * *'   # Every 15 minutes from 5:30 PM – 10:00 PM ET (22:30–30:00 UTC)


jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('googlesheets4', 'googledrive', 'dplyr', 'lubridate', 'stringr', 'rjson', 'httr', 'base64enc', 'magrittr', 'plyr', 'RCurl', 'XML'), repos = 'https://cloud.r-project.org')"

    - name: Check installed R packages
      run: |
        Rscript -e 'cat("Loaded packages:\n"); print(.packages())'
    
    - name: Run R script
      env:
        GCP_SHEETS_KEY_B64: ${{ secrets.GCP_SHEETS_KEY_B64 }}
      run: |
        Rscript "MLB DFS.R"

